export const actionTypes = {
    FATCHING_START: 'FATCHING_START',
    FATCHING_SUCCESS: 'FATCHING_SUCCESS',
    FATCHING_ERROR: 'FATCHING_ERROR',
    ADD_TO_CART: 'ADD_TO_CART',
    REMOVE_FROM_CART: 'REMOVE_FROM_CART',
    WISHLIST: 'WISHLIST',
};
